### ISSUE TITLE
Idea - pipe text files to piper or openedai-speech

### ISSUE THREAD

**Issue by ToeiRei** [rb81/ollama-feed-summarizer#1]
as you're writing text files, it wouldn't be a big deal to send those over to a TTS engine and make a mini-podcast for a daily briefing

**Comment by rb81** [comment]
@ToeiRei - Thanks for the suggestion. I've added the functionality using [OpenedAI Speech](https://github.com/matatonic/openedai-speech.git). If enabled, the script will generate an audio version of the summary and update the summary file with a link to the audio file.
